### ISSUE TITLE
Calibration bugs

### ISSUE THREAD

**Issue by bas-rustenburg** [choderalab/constph-openmm#36]
Opening a separate issue to discuss calibration API and bugs. Tagging @jchodera.

**Comment by bas-rustenburg** [comment]
Copy pasta from #34 

Basic explanation:
API is now this: `constph.constph.MonteCarloTitration` now has a `calibrate` method. Call this to converge. See `constph/examples/calibration_evaluation.py` for an example of how to use the API. I've been using this to debug.

This method sets up a `constph.calibration.AminoAcidCalibrator` for each of the detected amino acids. It has a `calibrate_till_converged` method to estimate whether SAMS estimates are converged. 
See `constph/examples/calibrator_eval.py` for a debugging script.

Under the hood:
The `AminoAcidCalibrator` sets up a `constph.calibration.CalibrationTitration`, while grabbing system files from  `constph/calibration-systems`.

The `CalibrationTitration` is a subclass of `MonteCarloTitration`, with SAMS implementation.

**Comment by jchodera** [comment]
Any other info on what I should be looking at?  Where does the actual SAMS happen?

**Comment by bas-rustenburg** [comment]
`constph.calibration.CalibrationTitration#adapt_weights`  contains the weights adaptation schemes.

**Comment by bas-rustenburg** [comment]
I think the issue may actually be related to insufficient configurational sampling. I doubled the number of steps and it became a lot closer to the target! Going to scale it up further.

**Comment by jchodera** [comment]
Did you double the number of steps/iteration or the number of iterations?

**Comment by bas-rustenburg** [comment]
Steps per iteration. Did another run with 10 times the amount of steps, but those weights look bad again, oddly enough...

**Comment by bas-rustenburg** [comment]
A weird inconsistency. I set the reference energies manually, and I observe different a histogram from when originally calibrated and running directly. Something is still quite wrong there.

**Comment by jchodera** [comment]
Can we find a few minutes to sit down together and have you walk me through your calibration code?

**Comment by bas-rustenburg** [comment]
@jchodera Just saw this. Do you have any time today?

**Comment by jchodera** [comment]
Sure. 4.00P?

**Comment by bas-rustenburg** [comment]
This has been fixed and merged in #42 and #41
